/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_assignment;


import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.JOptionPane;


/**
 *
 * @author Mannoj
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking2
     */
    public Booking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Viewver = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        rooomcombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        CheckInDates = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        CheckOutDates = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NOD = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        CustNames = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        IPass = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Number = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Mail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        boooking = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel2.setText("View");

        Viewver.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jungle", "Sea" }));
        Viewver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewverActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel3.setText("Room");

        rooomcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rooomcomboActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel4.setText("Check in");

        jLabel5.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel5.setText("Check out");

        jLabel6.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel6.setText("Number Of Days");

        NOD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        NOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NODActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel1.setText("Customer Name");

        CustNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustNamesActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel7.setText("IC/Passport");

        jLabel8.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel8.setText("Phone Number");

        jLabel10.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel10.setText("Email");

        jLabel9.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel9.setText("A deposit of RM100 will be automatically taken by payment through QR Code");

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        boooking.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        boooking.setText("Booking");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Back)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(boooking))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(Submit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CheckInDates, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(CheckOutDates, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rooomcombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NOD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CustNames)
                        .addComponent(IPass)
                        .addComponent(Number)
                        .addComponent(Mail))
                    .addComponent(Viewver, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(boooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Viewver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rooomcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(CheckInDates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckOutDates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(IPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CustNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(Mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addGap(69, 69, 69)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(Submit)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        String custname = CustNames.getText();
        String passport = IPass.getText();
        String pnumber = Number.getText();
        String mail = Mail.getText();
        
        if(custname.length()<4){
            JOptionPane.showMessageDialog(null, "Username too short");
            CustNames.setText("");
        }else if(custname.length()>12){
            JOptionPane.showMessageDialog(null, "Username too long");
            CustNames.setText("");
        } else if(!custname.matches("[a-zA-Z]+")){
            JOptionPane.showMessageDialog(null, "Only user lower or uppercase alphabets");
            CustNames.setText("");
        } else if(passport.length() != 12 || !passport.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid IC-number");
            IPass.setText("");
        } else if(pnumber.length() != 10){
            JOptionPane.showMessageDialog(null, "Please enter a valid phone number");
            Number.setText("");
        } else if(!mail.contains(".com")&&!mail.contains("@")){
            JOptionPane.showMessageDialog(null, "Please enter a valid email");
            Mail.setText("");
        } else{
            String View = Viewver.getSelectedItem().toString();
            String Room = rooomcombo.getSelectedItem().toString();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(CheckInDates.getDate());
            String CODate = CheckOutDates.getText();
            String NumberOfDays = NOD.getSelectedItem().toString();
            
            BookingFacts bd = new BookingFacts(View, Room, date, CODate, NumberOfDays, custname, passport, pnumber, mail);
            modifyCustDeet();
            new MainPage().setVisible(true);
            this.dispose(); 
        }
        


        
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void NODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NODActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        if((CheckInDates.getDate())==null){
            
        }
        else{
            String Checkindate = date.format(CheckInDates.getDate());
            int Days = Integer.parseInt(NOD.getSelectedItem().toString());
            LocalDate Id = LocalDate.parse(Checkindate);
            LocalDate checkoutdate = Id.plusDays(Days);
            CheckOutDates.setText(checkoutdate.toString());
           
        }
    }//GEN-LAST:event_NODActionPerformed

    private void ViewverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewverActionPerformed
        // TODO add your handling code here:
        String file;
            rooomcombo.removeAllItems();
            if(Viewver.getSelectedIndex()==0){
                file = "JungleView.txt";
                        
            }
            else {
                file = "SeaView.txt";
            }
            BufferedReader r = null;
            String l;
            try{
                r = new BufferedReader(new FileReader (file));
                int count = 0;
                while((l = r.readLine()) != null){
                   String[] array = l.split(",");
                   for(String a:array){
                       if (a.equals("Available")){
                           String roomID = array[0];
                           rooomcombo.addItem(roomID);
                       }
                   }
                }
            } 
            catch(IOException ef){
                ef.printStackTrace();
            } finally {
                try{
                    r.close();
                } catch (IOException ea){
                    ea.printStackTrace();
                }
            }
                    
    }//GEN-LAST:event_ViewverActionPerformed

    private void rooomcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rooomcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rooomcomboActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        new MainPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void CustNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustNamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustNamesActionPerformed
    public void modifyCustDeet(){
        String View = BookingFacts.getView();
        String Roomid = BookingFacts.getRoom();
        String CheckIn = BookingFacts.getCheckIn();
        String CheckOut = BookingFacts.getCheckOut();
        String NoDays = BookingFacts.getNOD();
        
        String Name = BookingFacts.getCustName();
        
        String IC = BookingFacts.getICNum();
        //String TotalA = Amo.getText();
        String pnumber = BookingFacts.getpnumber();
        String mail = BookingFacts.getmail();
        String details = Roomid + "," + "Available" + "," + "0" + "," + "0" + "," + "0" + "," + "0" + "," + "0" + "," + "0" + "," + "0" + "," + "0";
        String mod = Roomid + "," + "Rented" + "," + CheckIn + "," + CheckOut + "," + NoDays + "," + Name + "," + IC + "," + "RM100" + "," + pnumber + "," + mail;
        String file;
        String i = "";
        
        if(View.equals("Sea")){
            file = "SeaView.txt";
        } else{
            file = "JungleView.txt";
        }
        try {
            BufferedReader r = new BufferedReader(new FileReader(file));
            String l = r.readLine();
            while(l != null){
                i = i + l + System.lineSeparator();
                l = r.readLine();
            }
            String newC = i.replaceAll(details, mod);
            FileWriter w = new FileWriter(file);
            
            w.write(newC);
            w.close();
            r.close();
            
        }
        catch(IOException e){
            e.printStackTrace();
        }
    }
    
    private void payment(){
        final double RoomAmount = 350;
        final double TaxTourism = 10;
        final double TaxService = 0.1;

        double days = Integer.parseInt(BookingFacts.getNOD());

        double hTotal = RoomAmount * days;//700
        double aTotal = TaxService * hTotal;//htotal * 0.1 = 70
        double rTotal = TaxTourism * days;// =20
        double TotalAmount = hTotal + aTotal + rTotal;
      
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }
    
   
    
    public class BookingFacts {
        private static String View, Room, CheckIn, CheckOut, NOD, CustName, ICNum, pnumber, mail;
        public BookingFacts(String View, String Room, String CheckIn, String CheckOut, String NOD, String CustName, String ICNum, String pnumber, String mail){
            BookingFacts.View = View;
            BookingFacts.Room = Room;
            BookingFacts.CheckIn = CheckIn;
            BookingFacts.CheckOut = CheckOut;
            BookingFacts.NOD = NOD;
            BookingFacts.CustName = CustName;
            BookingFacts.ICNum = ICNum;
            BookingFacts.pnumber = pnumber;
            BookingFacts.mail = mail;
            
        }
        public static String getView(){
            return View;
        }
        public static String getRoom(){
            return Room;
        }
        public static String getCheckIn(){
            return CheckIn;
        }
        public static String getCheckOut(){
            return CheckOut;
        }
        public static String getNOD(){
            return NOD;
        }
        public static String getCustName(){
            return CustName;
        }
        public static String getICNum(){
            return ICNum;
        }
        public static String getpnumber(){
            return pnumber;
        }
        public static String getmail(){
            return mail;
        }
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private com.toedter.calendar.JDateChooser CheckInDates;
    private javax.swing.JTextField CheckOutDates;
    private javax.swing.JTextField CustNames;
    private javax.swing.JTextField IPass;
    private javax.swing.JTextField Mail;
    private javax.swing.JComboBox<String> NOD;
    private javax.swing.JTextField Number;
    private javax.swing.JButton Submit;
    private javax.swing.JComboBox<String> Viewver;
    private javax.swing.JLabel boooking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> rooomcombo;
    // End of variables declaration//GEN-END:variables

    
}
